import { Product } from './product.model';
import { Category } from './category.model';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Fun & Quirky' },
  { id: 2, name: 'Plush Toys' },
  { id: 3, name: 'Soft & Cozy' },
  { id: 4, name: 'Character Toys' },
];

export const PRODUCTS: Product[] = [

  // categoryId: 1o
  {
    id: 1,
    name: 'Octopus Flip Toy',
    description: 'Flip it inside out and it changes color! This octopus has more mood swings than you do. Well, at least its cute about it',
    price: 1290,
    rating: 4.6,
    image: 'assets/images/octopus/1.jpg',
    images: ['assets/images/octopus/1.jpg', 'assets/images/octopus/2.jpeg', 'assets/octopus/lapka/3.jpeg'],
    link: 'https://kaspi.kz/shop/p/octopus-mjagkaja-igrushka-os-minog-perevertysh-vysota-10-sm-goluboi-rozovyi-106657073/?c=750000000',
    likes: 0,
    categoryId: 1,
  },
  {
    id: 2,
    name: 'Cat Pushin',
    description: 'Push him and he comes back. Just like that one person who never takes a hint. Grey, soft, and emotionally unavailable.',
    price: 1990,
    rating: 4.5,
    image: 'assets/images/pushin/1.jpeg',
    images: ['assets/images/pushin/1.jpeg', 'assets/images/pushin/2.jpg', 'assets/images/pushin/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-kot-pushin-aa-142-vysota-15-sm-seryi-109641025/?c=750000000',
    likes: 0,
    categoryId: 1,
  },
  {
    id: 3,
    name: 'Googly Eye Cat',
    description: 'This cat has eyes bigger than its life choices. Very soft, very white, very judgy. It stares into your soul and finds it disappointing.',
    price: 2490,
    rating: 4.7,
    image: 'assets/images/googly-cat/1.jpeg',
    images: ['assets/images/googly-cat/1.jpeg', 'assets/images/googly-cat/2.jpeg', 'assets/images/googly-cat/3.jpeg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-kotik-glazastik-vysota-23-sm-belyi-seryi-130380044/?c=750000000',
    likes: 0,
    categoryId: 1,
  },
  {
    id: 4,
    name: 'Labubu Toy',
    description: 'The trendy little gremlin everyone is obsessed with. Is it cute? Is it scary? Nobody knows. Just buy it before it sells out again.',
    price: 3990,
    rating: 4.9,
    image: 'assets/images/labubu/1.jpeg',
    images: ['assets/images/labubu/1.jpeg', 'assets/images/labubu/2.jpg', 'assets/images/labubu/3.webp'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-1001-labubu-28-sm-rozovyi-141270310/?c=750000000',
    likes: 0,
    categoryId: 1,
  },
  {
    id: 5,
    name: 'Giant Shark Toy',
    description: '100cm of pure shark energy. Baby shark doo doo doo.',
    price: 6990,
    rating: 4.8,
    image: 'assets/images/shark/1.jpeg',
    images: ['assets/images/shark/1.jpeg', 'assets/images/shark/2.jpeg', 'assets/images/shark/3.jpeg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-home-tech-shark-100-sm-belyi-rozovyi-145387116/?c=750000000',
    likes: 0,
    categoryId: 1,
  },

  // categoryId: 2
  {
    id: 6,
    name: 'Taba Paw Pillow Toy',
    description: 'Soft pillow toy with a plush blanket. Very cozy and trendy bro, please buy it. Please im broke. Im begging you. PLEASE.',
    price: 3990,
    rating: 4.7,
    image: 'assets/images/lapka/1.jpeg',
    images: ['assets/images/lapka/1.jpeg', 'assets/images/lapka/2.jpg', 'assets/images/lapka/3.jpg'],
    link: 'https://kaspi.kz/shop/p/podushka-igrushka-kazimport-mjagkaja-igrushka-s-pledom-igrushka-podushka-taba-lapka-45-sm-belyi-rozovyi-132778055/?c=750000000',
    likes: 0,
    categoryId: 2,
  },
  {
    id: 7,
    name: 'Stupid Looking Sheep',
    description: 'Fluffy sheep, soft, pleasant to the touch, completely safe from birth. Very demure. But she looks a bit stupid though. No offence sheep.',
    price: 1990,
    rating: 4.5,
    image: 'assets/images/sheep/1.jpg',
    images: ['assets/images/sheep/1.jpg', 'assets/images/sheep/2.jpg', 'assets/images/sheep/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-ovechka-vysota-25-sm-belyi-117673009/?c=750000000',
    likes: 0,
    categoryId: 2,
  },
  {
    id: 8,
    name: 'Cat Baton Pillow Toy',
    description: 'Anti-stress pillow toy in the shape of a cat. Its very very very very very very very very very very long. And soft. Thats it.',
    price: 4490,
    rating: 2.8,
    image: 'assets/images/kot-baton/1.jpg',
    images: ['assets/images/kot-baton/1.jpg', 'assets/images/kot-baton/2.jpeg', 'assets/images/kot-baton/3.jpeg'],
    link: 'https://kaspi.kz/shop/p/podushka-igrushka-kot-baton-vysota-50-sm-belyi-seryi-106870636/?c=750000000',
    likes: 0,
    categoryId: 2,
  },
  {
    id: 9,
    name: 'Hooded Teddy Bear Toy',
    description: 'His hoodie is the best among other bears. Super fashionista, every bro gets jealous. Buy this bear and receive not only a bear but also a loyal bro.',
    price: 2790,
    rating: 4.6,
    image: 'assets/images/bear-hood/1.jpeg',
    images: ['assets/images/bear-hood/1.jpeg', 'assets/images/bear-hood/2.jpeg', 'assets/images/bear-hood/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-mishka-s-kapjushonom-574164-vysota-28-sm-rozovyi-114957927/?c=750000000',
    likes: 0,
    categoryId: 2,
  },
  {
    id: 10,
    name: 'Giant Teddy Bear',
    description: 'This bear is 160cm tall. Taller than most of your friends. Lol!!!',
    price: 15990,
    rating: 4.9,
    image: 'assets/images/giant-bear/1.jpg',
    images: ['assets/images/giant-bear/1.jpg', 'assets/images/giant-bear/2.jpg', 'assets/images/giant-bear/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-mjagkii-mishka-vysota-160-sm-rozovyi-101750718/?c=750000000',
    likes: 0,
    categoryId: 2,
  },

  // categoryId: 3
  {
    id: 11,
    name: 'Strawberry Bunny Toy',
    description: 'Unique transformer: a strawberry turns into a bunny! Do not let your kids eat the strawberry form unless you want your kids dead. Well then yea why not.',
    price: 2490,
    rating: 4.9,
    image: 'assets/images/strabwerry-bunny/1.jpg',
    images: ['assets/images/strabwerry-bunny/1.jpg', 'assets/images/strabwerry-bunny/2.jpg', 'assets/images/strabwerry-bunny/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-zajats-klubnika-vysota-25-sm-rozovyi-112395188/?c=750000000',
    likes: 0,
    categoryId: 3,
  },
  {
    id: 12,
    name: 'Bunny Mi Pillow Toy',
    description: 'Omg very stupid and lazy. Bunny just lays on her belly the whole day doing nothing absolutely. If you want someone who resembles you, please buy this toy.',
    price: 5990,
    rating: 4.7,
    image: 'assets/images/bunny-mi/1.jpg',
    images: ['assets/images/bunny-mi/1.jpg', 'assets/images/bunny-mi/2.jpg', 'assets/images/bunny-mi/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-pled-zaichik-a-05-vysota-60-sm-rozovyi-108338629/?c=750000000',
    likes: 0,
    categoryId: 3,
  },
  {
    id: 13,
    name: 'Penguin Toy',
    description: 'She is super cute and her backpack too. Very demure and petite. Idk what else to say.',
    price: 2790,
    rating: 4.5,
    image: 'assets/images/penguin/1.jpg',
    images: ['assets/images/penguin/1.jpg', 'assets/images/penguin/2.jpg', 'assets/images/penguin/3.webp'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-1toy-pingvin-devochka-25-sm-belyi-seryi-138941775/?c=750000000',
    likes: 0,
    categoryId: 3,
  },
  {
    id: 14,
    name: 'Piggy with Bow',
    description: 'A pig with a bow. Pig looks very official, shes going to very important meeting ig.',
    price: 1890,
    rating: 4.3,
    image: 'assets/images/bow-pig/1.jpeg',
    images: ['assets/images/bow-pig/1.jpeg', 'assets/images/bow-pig/2.jpeg', 'assets/images/bow-pig/3.jpeg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-porosenok-s-bantikom-i-tsvetochkom-22-sm-svetlo-rozovyi-154742867/?c=750000000',
    likes: 0,
    categoryId: 3,
  },
  {
    id: 15,
    name: 'Cappuccino Ballerina Toy',
    description: 'Ballerina Cappuccina, mi-mi-mi È la moglie di Cappuccino Assassino. E ama la musica la-la-la. La sua passione è il ballerino. Lololo.',
    price: 2290,
    rating: 4.6,
    image: 'assets/images/ballerina/1.jpeg',
    images: ['assets/images/ballerina/1.jpeg', 'assets/images/ballerina/2.jpeg', 'assets/images/ballerina/3.jpeg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-balerina-kapuchino-25-sm-belyi-140985302/?c=750000000',
    likes: 0,
    categoryId: 3,
  },

  // categoryId: 4
  {
    id: 16,
    name: 'Kuromi Toy',
    description: 'Adorable Kuromi plush toy! Buy it and love it. If she likes you back she will bring money and happiness. Otherwise she will burn everyone in hell!',
    price: 2990,
    rating: 4.8,
    image: 'assets/images/kuromi/1.jpeg',
    images: ['assets/images/kuromi/1.jpeg', 'assets/images/kuromi/2.jpeg', 'assets/images/kuromi/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-kuromi-vysota-33-sm-mul-tikolor-rozovyi-115569503/?c=750000000',
    likes: 0,
    categoryId: 4,
  },
  {
    id: 17,
    name: 'My Melody Toy',
    description: 'Unlike Kuromi, My Melody is an angel. Just look at her omg. My shayla and stuff. Just buy her okay?',
    price: 3290,
    rating: 3.9,
    image: 'assets/images/my-melody/1.jpg',
    images: ['assets/images/my-melody/1.jpg', 'assets/images/my-melody/2.jpeg', 'assets/images/my-melody/3.webp'],
    link: 'https://kaspi.kz/shop/p/podushka-igrushka-my-melody-vysota-33-sm-rozovyi-132747441/?c=750000000',
    likes: 0,
    categoryId: 4,
  },
  {
    id: 18,
    name: 'Hello Kitty Toy',
    description: 'She is super cute! Did you know shes 50+ years old?',
    price: 3490,
    rating: 4.7,
    image: 'assets/images/hello-kitty/1.jpg',
    images: ['assets/images/hello-kitty/1.jpg', 'assets/images/hello-kitty/2.jpg', 'assets/images/hello-kitty/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-hello-kitty-kitty-vysota-30-sm-mul-tikolor-107746457/?c=750000000',
    likes: 0,
    categoryId: 4,
  },
  {
    id: 19,
    name: 'Pinkie Pie Pony',
    description: 'Come on every pony, smile, smile, SMILE!! Fill my heart up with sunshine SUNSHINE!!',
    price: 2190,
    rating: 4.4,
    image: 'assets/images/pinkie-pie/1.jpeg',
    images: ['assets/images/pinkie-pie/1.jpeg', 'assets/images/pinkie-pie/2.jpeg', 'assets/images/pinkie-pie/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-poni-vysota-20-sm-rozovyi-110224836/?c=750000000',
    likes: 0,
    categoryId: 4,
  },
  {
    id: 20,
    name: 'Miserable Minecraft Pig',
    description: 'Plush pig from the Minecraft universe. It looks so miserable it may cause anxiety and depression. But its pig from MINECRAFT, what can be better than that?',
    price: 1790,
    rating: 1.7,
    image: 'assets/images/minecraft-pig/1.jpg',
    images: ['assets/images/minecraft-pig/1.jpg', 'assets/images/minecraft-pig/2.jpg', 'assets/images/minecraft-pig/3.jpg'],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-minecraft-pig-vysota-15-sm-rozovyi-129996149/?c=750000000',
    likes: 0,
    categoryId: 4,
  },
];